import React, { useState, useEffect } from 'react';
import { Select, SelectItem, Button } from '@nextui-org/react';
import { FiGlobe } from 'react-icons/fi';
import { brandColors } from '../theme';

// Доступные языки с их кодами и названиями
const AVAILABLE_LANGUAGES = [
  { code: 'ru', name: 'Русский', nativeName: 'Русский' },
  { code: 'uz', name: 'Узбекский', nativeName: 'O\'zbekcha' },
  { code: 'en', name: 'Английский', nativeName: 'English' }
];

// Переводы для основных элементов интерфейса
const translations = {
  ru: {
    selectLanguage: 'Выберите язык',
    language: 'Язык',
    home: 'Главная',
    findDoctor: 'Найти врача',
    history: 'История',
    profile: 'Профиль',
    logout: 'Выйти',
    login: 'Войти',
    register: 'Регистрация',
    search: 'Поиск',
    specialization: 'Специализация',
    city: 'Город',
    country: 'Страна',
    price: 'Цена',
    verifiedDoctor: 'Верифицированный врач',
    experience: 'Опыт работы',
    organization: 'Организация',
    position: 'Должность',
    years: 'Годы работы',
    languages: 'Языки',
    consultation: 'Консультация',
    reviews: 'Отзывы',
    rating: 'Рейтинг',
    about: 'О враче',
    education: 'Образование',
    workExperience: 'Опыт работы',
    cost: 'Стоимость консультации',
    loading: 'Загрузка...',
    noResults: 'Результаты не найдены',
    error: 'Произошла ошибка',
    patient: 'Пациент',
    doctor: 'Врач',
    admin: 'Администратор',
    user: 'Пользователь',
    notifications: 'Уведомления',
    markAllRead: 'Отметить все как прочитанные',
    newNotification: 'Новое',
    expand: 'Подробнее',
    collapse: 'Свернуть',
    profileSettings: 'Настройки профиля',
    adminPanel: 'Админ-панель',
    selectSpecialization: 'Выберите специализацию',
    allSpecializations: 'Все специализации',
    selectCity: 'Выберите город',
    allCities: 'Все города',
    selectLanguage: 'Выберите язык',
    allLanguages: 'Все языки',
    searching: 'Поиск...',
    location: 'Местоположение',
    notSpecified: 'Не указано',
    organizations: 'организаций',
    languages: 'Языки общения:',
    emailRequired: 'Пожалуйста, введите email',
    passwordRequired: 'Пожалуйста, введите пароль',
    invalidEmail: 'Пожалуйста, введите корректный email',
    loginError: 'Произошла ошибка при входе. Попробуйте позже.',
    emailPlaceholder: 'Введите ваш email',
    passwordPlaceholder: 'Введите ваш пароль',
    currentPasswordRequired: 'Пожалуйста, введите текущий пароль',
    newPasswordRequired: 'Пожалуйста, введите новый пароль',
    passwordMinLength: 'Новый пароль должен содержать минимум 8 символов',
    passwordMismatch: 'Пароли не совпадают',
    passwordSameAsCurrent: 'Новый пароль должен отличаться от текущего',
    securityError: 'Ошибка безопасности. Пожалуйста, обновите страницу и попробуйте снова.',
    changePhoto: 'Изменить фото',
    saveChanges: 'Сохранить изменения',
    currentPassword: 'Текущий пароль',
    newPassword: 'Новый пароль',
    confirmPassword: 'Подтверждение пароля',
    practiceDistrict: 'Район практики',
    workExperience: 'Опыт работы (лет)',
    cityRegion: 'Город/Регион',
    password: 'Пароль',
    rememberMe: 'Запомнить меня',
    forgotPassword: 'Забыли пароль?',
    noAccount: 'Нет аккаунта?',
    phoneNumber: 'Номер телефона',
    fullNameRequired: 'Пожалуйста, введите ваше полное имя',
    phoneRequired: 'Пожалуйста, введите номер телефона',
    cityRegionRequired: 'Пожалуйста, выберите город/область',
    districtRequired: 'Пожалуйста, выберите район',
    confirmPasswordRequired: 'Пожалуйста, подтвердите пароль',
    passwordMinimum: 'Пароль должен содержать не менее 8 символов',
    termsRequired: 'Для регистрации необходимо согласиться с условиями использования',
    registrationError: 'Ошибка при регистрации. Пожалуйста, попробуйте позже.',
    registrationSuccess: 'Регистрация успешна!',
    verificationEmailSent: 'Мы отправили письмо с подтверждением на адрес',
    verificationInstructions: 'Пожалуйста, проверьте вашу почту и перейдите по ссылке в письме для активации аккаунта.',
    goToLogin: 'Перейти на страницу входа',
    accountCreatedSuccess: 'Ваш аккаунт успешно создан. Теперь вы можете войти в систему, используя указанные учетные данные.',
    noVerificationEmail: 'Не получили письмо? Проверьте папку "Спам" или',
    resendEmail: 'отправить повторно',
    basicInfo: 'Основная информация',
    securityInfo: 'Безопасность',
    locationInfo: 'Местоположение',
    additionalInfo: 'Дополнительная информация',
    agreeToTerms: 'Я соглашаюсь с',
    termsOfService: 'условиями использования',
    and: 'и',
    privacyPolicy: 'политикой конфиденциальности',
    createAccount: 'Создать аккаунт',
    haveAccount: 'Уже есть аккаунт?',
    platformDescription: 'Медицинская платформа для онлайн-консультаций с лучшими специалистами',
    alreadyGoogleRegistered: 'Уже зарегистрированы через Google?',
    loginWithGoogle: 'Войти через Google',
    or: 'Или',
    loginRegister: 'Вход, регистрация',
    platformAdvantages: 'Преимущества нашей платформы:',
    convenientDoctorSearch: 'Удобный поиск врачей по специализации',
    onlineConsultationsAnywhere: 'Онлайн-консультации из любой точки мира',
    secureDataExchange: 'Защищенный обмен медицинскими данными',
    needHelp: 'Нужна помощь?',
    contactUs: 'Свяжитесь с нами',
    enterFullName: 'Введите ваше ФИО',
    enterEmail: 'Введите ваш email',
    enterPhoneNumber: 'Введите ваш номер телефона',
    enterPassword: 'Введите пароль',
    enterConfirmPassword: 'Подтвердите пароль',
    selectCityRegion: 'Выберите ваш город или область',
    selectDistrict: 'Выберите ваш район',
    enterAddress: 'Введите ваш адрес',
    loginSystemAccess: 'Войдите в систему для доступа к медицинским консультациям',
    createNewAccount: 'Создать новый аккаунт',
    adminAccess: 'Вход для администраторов',
    registerForConsultations: 'Зарегистрируйтесь для получения консультаций от специалистов',
    loginTab: 'Вход',
    registerTab: 'Регистрация',
    googleLogin: 'Вход через Google',
    googleLoginHint: 'Если вы зарегистрировались через Google, пожалуйста, используйте кнопку',
    belowText: 'ниже.',
    googleLoginTooltip: 'Если вы зарегистрировались через Google, используйте кнопку \'Войти через Google\' выше',
    medicalInfoPlaceholder: 'Введите информацию о хронических заболеваниях, аллергиях и т.д.',
    agreeWith: 'Я согласен с',
    registerButton: 'Зарегистрироваться',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    loginLink: 'Войти',
    minimumChars: 'Минимум 8 символов',
    repeatPassword: 'Повторите пароль',
    passwordsDontMatch: 'Пароли не совпадают',
    // Дополнительные переводы
    welcome: 'Добро пожаловать в Soglom',
    subtitle: 'Ваш цифровой помощник в области здравоохранения',
    getStarted: 'Начать',
    howItWorks: 'Как это работает',
    findDoctors: 'Найти врачей',
    bookAppointment: 'Записаться на прием',
    consultOnline: 'Консультироваться онлайн',
    step: 'Шаг',
    chooseDoctor: 'Выберите врача',
    chooseDoctorDesc: 'Найдите подходящего специалиста среди наших проверенных врачей',
    scheduleAppointment: 'Запланируйте встречу',
    scheduleAppointmentDesc: 'Выберите удобное время для консультации',
    getConsultation: 'Получите консультацию',
    getConsultationDesc: 'Получите качественную медицинскую помощь онлайн или офлайн',
    verifiedDoctors: 'Проверенные врачи',
    onlineConsultations: 'Онлайн консультации',
    securePayments: 'Безопасные платежи',
    featuredDoctors: 'Рекомендуемые врачи',
    viewProfile: 'Посмотреть профиль',
    becomeDoctor: 'Стать врачом',
    moreDetails: 'Подробнее',
    bookNow: 'Записаться',
    fullName: 'Полное имя',
    contactPhone: 'Контактный телефон',
    address: 'Адрес',
    district: 'Район',
    medicalInfo: 'Медицинская информация',
    editProfile: 'Редактировать профиль',
    profileInfo: 'Информация профиля',
    save: 'Сохранить',
    cancel: 'Отмена',
    required: 'Обязательное поле',
    phoneInvalid: 'Неверный формат номера телефона',
    profileSaved: 'Профиль успешно сохранен!',
    profileNotCreated: 'Профиль еще не создан. Пожалуйста, заполните информацию.',
    pleaseCompleteBefore: 'Пожалуйста, заполните информацию ниже.',
    settings: 'Настройки',
    changePassword: 'Сменить пароль',
    updatePasswordSecurity: 'Обновите пароль для безопасности',
    notificationSettings: 'Настройки уведомлений',
    manageNotifications: 'Управление уведомлениями',
    deleteAccount: 'Удалить аккаунт',
    deleteAccountPermanently: 'Удалить аккаунт навсегда',
    security: 'Безопасность',
    passwordSecuritySettings: 'Управление паролем и настройками безопасности вашего аккаунта',
    authSuccess: 'Авторизация успешна!',
    authProcessing: 'Завершение авторизации...',
    authProcessingDescription: 'Пожалуйста, подождите, мы обрабатываем вашу авторизацию через Google.',
    authErrorTitle: 'Ошибка авторизации',
    authRedirectMessage: 'Вы будете перенаправлены на главную страницу...',
    returnToLogin: 'Вернуться на страницу входа',
    consultationStarted: 'Консультация успешно началась',
    thanksForReview: 'Спасибо за ваш отзыв!',
    redirectingHome: 'Перенаправление на главную страницу...',
    emailVerified: 'Email подтвержден успешно!',
    emailAlreadyVerified: 'Email уже был успешно подтвержден! Переходим в профиль...',
    newVerificationSent: 'Новая ссылка для подтверждения отправлена на указанную почту',
    emailAlreadyConfirmed: 'уже подтвержден. Добро пожаловать!',
    emailSuccessfullyVerified: 'Email успешно подтвержден. Добро пожаловать!',
    profileCreatedFromRegistration: 'Профиль успешно создан с данными из регистрации!',
    consultationRequestSent: 'Заявка на консультацию успешно отправлена!',
    pushNotificationsEnabled: 'Push-уведомления включены!',
    passwordChanged: 'Пароль успешно изменен',
    profilePhotoUpdated: 'Фото профиля успешно обновлено',
    notificationSettingsSaved: 'Настройки уведомлений сохранены',
    accountDeleted: 'Аккаунт успешно удален',
    reviewAlreadySent: 'Отзыв уже был отправлен',
    reviewSent: 'Отзыв успешно отправлен',
    avatarUpdated: 'Аватар успешно обновлен',
    consultationCompleted: 'Консультация успешно завершена',
    consultationAutoCompleted: 'Консультация автоматически завершена из-за достижения лимита сообщений',
    
    // Дополнительные переводы для Google авторизации
    attention: 'Внимание',
    extensionWarning: 'Обнаружены расширения браузера, которые могут мешать процессу авторизации. Если возникают проблемы, попробуйте временно отключить расширения или использовать режим инкогнито.',
    authErrorCodeExpired: 'Код авторизации истек или недействителен. Пожалуйста, попробуйте войти снова.',
    authErrorCodeUsed: 'Этот код авторизации уже был использован. Пожалуйста, войдите снова.',
    authErrorGeneric: 'Произошла ошибка при обработке авторизации через Google. Пожалуйста, попробуйте еще раз.',
    
    // Дополнительные системные сообщения
    connectionLost: 'Соединение с сервером потеряно. Попробуйте позже.',
    messageSendFailed: 'Не удалось отправить сообщение. Попробуйте еще раз.',
    connectionError: 'Не удалось установить соединение с сервером.',
    chatLoadError: 'Ошибка при загрузке чата. Попробуйте обновить страницу.',
    serverConnectionFailed: 'Не удалось подключиться к серверу',
    connectingToServer: 'Подключение к серверу...',
    finalizingConsultation: 'Завершение консультации...',
    consultationCompletedSuccess: 'Консультация успешно завершена',
    completionFailed: 'Не удалось завершить консультацию. Пожалуйста, обновите страницу и попробуйте еще раз.',
    autoCompletionFailed: 'Не удалось автоматически завершить консультацию. Обратитесь к врачу.',
    messageLimitReached: 'Достигнут лимит сообщений. Консультация будет завершена.',
    messageLimitAutoComplete: 'Консультация автоматически завершена из-за достижения лимита сообщений',
    connectionTimeout: 'Превышено количество попыток подключения. Пожалуйста, обновите страницу.',
    unknownError: 'Произошла неизвестная ошибка',
    statusActive: 'Активна',
    statusCompleted: 'Завершена',
    statusWaiting: 'Ожидание',
    startChatMessage: 'Начните диалог, отправив первое сообщение',
    waitForStart: 'Дождитесь начала консультации',
    reviewFormError: 'Не удалось открыть форму отзыва',
    messagePlaceholder: 'Введите сообщение...',
    sendingDisabled: 'Отправка сообщений недоступна',
    messageLimitReachedStatus: 'Достигнут лимит сообщений',
    refreshChat: 'Обновить чат',
    loadingMessages: 'Загрузка сообщений...',
    finishConsultation: 'Завершить консультацию',
    noMessages: 'Нет сообщений',
    startConversation: 'Начните диалог, отправив первое сообщение',
    waitForConsultation: 'Дождитесь начала консультации',
    messagingDisabled: 'Отправка сообщений недоступна',
    enterMessage: 'Введите сообщение...',
    messageLimitExceeded: 'Вы достигли лимита сообщений для этой консультации',
    completeConsultation: 'Завершение консультации',
    confirmCompleteConsultation: 'Вы уверены, что хотите завершить консультацию? После завершения отправка сообщений будет недоступна.',
    patientCanLeaveReview: 'Пациент получит возможность оставить отзыв о консультации.',
    
    // Переводы для ReviewForm
    leaveReview: 'Оставить отзыв',
    consultationWith: 'Консультация с',
    reviewHelpMessage: 'Ваш отзыв поможет другим пациентам выбрать подходящего врача. Спасибо за обратную связь!',
    rateConsultation: 'Как вы оцениваете консультацию?',
    ratingVeryBad: 'Очень плохо',
    ratingBad: 'Плохо', 
    ratingNormal: 'Нормально',
    ratingGood: 'Хорошо',
    ratingExcellent: 'Отлично',
    yourComment: 'Ваш комментарий',
    reviewCommentPlaceholder: 'Расскажите о вашем опыте консультации...',
    commentHelpText: 'Ваш комментарий поможет врачу улучшить качество консультаций',
    submitReview: 'Отправить отзыв',
    reviewSubmitError: 'Не удалось отправить отзыв. Пожалуйста, попробуйте позже.',
    
    // Переводы для DoctorProfilePage
    bookConsultation: 'Записаться на консультацию',
    doctorInfo: 'Информация о враче',
    practiceLocation: 'Местоположение практики',
    specializations: 'Специализации',
    consultationLanguages: 'Языки консультаций', 
    doctorReviews: 'Отзывы о враче',
    reviewWithoutComment: 'Отзыв без комментария',
    doctorPracticeRegion: 'Регион практики врача',
    noDoctorReviews: 'У этого врача пока нет отзывов',
    beFirstToReview: 'Будьте первым, кто оставит отзыв после консультации',
    
    // Переводы для SearchDoctorsPage
    findSpecialistDescription: 'Найдите подходящего специалиста для консультации',
    searchInRegion: 'Поиск в регионе',
    autoFilterByRegion: 'Врачи фильтруются автоматически по вашему региону. Изменить можно в настройках профиля.',
    doctorsFound: 'Найдено врачей',
    searchResults: 'Результаты поиска',
    page: 'Страница',
    of: 'из',
    noDoctorsFound: 'Нет врачей, соответствующих вашим критериям поиска',
    tryChangeSearchParams: 'Попробуйте изменить параметры поиска или выбрать другую специализацию',
    
    // Переводы для HomePage
    findDoctorDescription: 'Поиск врачей по специализации и записаться на консультацию',
    historyDescription: 'Просмотр истории ваших консультаций и платежей',
    profileSettingsDescription: 'Обновление личной информации и настройки аккаунта',
    myConsultations: 'Мои консультации',
    myConsultationsDescription: 'Управление текущими и предстоящими консультациями',
    doctorProfileDescription: 'Обновление профессиональной информации и расписания',
    analytics: 'Аналитика',
    analyticsDescription: 'Статистика консультаций и отзывы пациентов',
    doctorWelcomeMessage: 'Здесь вы можете управлять консультациями и настраивать ваш профиль.',
    patientWelcomeMessage: 'Здесь вы можете искать врачей, управлять консультациями и просматривать историю.',
    emailVerificationRequired: 'Требуется подтверждение Email',
    emailVerificationMessage: 'Вы не можете использовать полный функционал платформы, пока не подтвердите свой Email. Пожалуйста, проверьте вашу почту и перейдите по ссылке в письме.',
    havingProblems: 'Возникли проблемы?',
    goTo: 'Перейти',
    goToAdminPanel: 'Перейти в админ-панель',
    contactSupport: 'Связаться с поддержкой',
    systemManagement: 'Управление системой и пользователями',
    adminPanelDescription: 'Управление пользователями и заявками врачей',
    systemAnalytics: 'Аналитика системы',
    platformUsageStats: 'Статистика использования платформы',
    featureInDevelopment: 'Функционал в разработке',
        inDevelopment: 'В разработке',
    
    // Переводы для AdminPage
    adminPanelTitle: 'Панель администратора',
    systemUserManagement: 'Управление системой и пользователями',
    administrativePanel: 'Административная панель',
    account: 'Аккаунт',
    role: 'Роль',
    administrator: 'Администратор',
    doctorApplications: 'Заявки врачей',
    doctorRoleApplications: 'Заявки на получение роли врача',
    pending: 'Ожидающие',
    approved: 'Одобренные',
    rejected: 'Отклоненные',
    all: 'Все',
    users: 'Пользователи',
    userManagement: 'Управление пользователями',
    refreshList: 'Обновить список',
    noUsersInSystem: 'Нет пользователей в системе',
    notifications: 'Уведомления',
    notificationManagement: 'Управление уведомлениями',
    browserPushStatus: 'Статус браузерных push-уведомлений',
    browserSupport: 'Поддержка браузера',
    supported: 'Поддерживается',
    notSupported: 'Не поддерживается',
    permission: 'Разрешение',
    allowed: 'Разрешено',
    blocked: 'Заблокировано',
    notDetermined: 'Не определено',
    requestPermission: 'Запросить разрешение',
    testBrowserNotifications: 'Тестировать браузерные уведомления',
    notificationTitle: 'Заголовок уведомления',
    notificationText: 'Текст уведомления',
    notificationType: 'Тип уведомления',
    system: 'Системное',
    consultation: 'Консультация',
    appointment: 'Запись',
    message: 'Сообщение',
    update: 'Обновление',
    recipientParams: 'Параметры получателей',
    sendToAll: 'Всем пользователям',
    sendByRole: 'По роли пользователя',
    sendToSpecific: 'Конкретному пользователю',
    selectRole: 'Выберите роль',
    userIdForNotification: 'ID пользователя для уведомления',
    sendNotification: 'Отправить уведомление',
    sendWebSocketNotifications: 'Отправка WebSocket уведомлений',
    personalData: 'Персональные данные',
    fullName: 'Полное имя',
    phoneNumber: 'Номер телефона',
    role: 'Роль',
    registrationDate: 'Дата регистрации',
    specialization: 'Специализация',
    changeRole: 'Изменить роль',
    newRole: 'Новая роль',
    
    // Статусы консультаций
    completed: 'Завершена',
    active: 'Активна',
    pending: 'Ожидает',
    cancelled: 'Отменена',
    unknown: 'Неизвестно',
    
    // Дополнительные переводы для HistoryPage
    doctor: 'Врач',
    patient: 'Пациент',
    status: 'Статус',
    creationDate: 'Дата создания',
    startTime: 'Время начала',
    noConsultationsHistory: 'У вас пока нет истории консультаций',
    loadingHistory: 'Загрузка истории...',
    failedToLoadHistory: 'Не удалось загрузить историю консультаций. Пожалуйста, попробуйте позже.',
    failedToLoadUnreadMessages: 'Не удалось загрузить непрочитанные сообщения, используем кэшированные данные',
    
    // Переводы для PatientProfileForm
    consultationHistoryWillBeUnavailable: 'История консультаций будет недоступна',
    editProfile: 'Редактировать профиль',
    saveProfile: 'Сохранить профиль',
    cancelEditing: 'Отменить редактирование',
    changePassword: 'Изменить пароль',
    notificationSettings: 'Настройки уведомлений',
    privacySettings: 'Настройки приватности',
    deleteAccount: 'Удалить аккаунт',
    currentPassword: 'Текущий пароль',
    newPassword: 'Новый пароль',
    confirmPassword: 'Подтвердите пароль',
    emailNotifications: 'Email уведомления',
    pushNotifications: 'Push уведомления',
    appointmentReminders: 'Напоминания о записях',
    medicalInfo: 'Медицинская информация',
    medicalInfoPlaceholder: 'Хронические заболевания, аллергии, принимаемые препараты...',
    profileImageUpload: 'Загрузка фото профиля',
    selectPhoto: 'Выберите фото',
    changePhoto: 'Изменить фото',
    profileSaved: 'Профиль сохранен',
    profileSaveError: 'Ошибка при сохранении профиля',
    passwordChanged: 'Пароль изменен',
    passwordChangeError: 'Ошибка при изменении пароля',
    notificationSettingsUpdated: 'Настройки уведомлений обновлены',
    deleteAccountConfirmation: 'Вы уверены, что хотите удалить аккаунт?',
    thisActionCannotBeUndone: 'Это действие нельзя отменить',
    selectRegion: 'Выберите область',
    selectDistrict: 'Выберите район',
    
    // Переводы для RequestConsultationModal
    youAlreadyHaveConsultation: 'У вас уже есть консультация',
    consultationApplication: 'Заявка на консультацию',
    consultationRequestSent: 'Заявка на консультацию отправлена',
    consultationRequestError: 'Ошибка при отправке заявки на консультацию',
    consultationAlreadyActive: 'У вас уже есть активная консультация с этим врачом',
    goToConsultations: 'Перейти к консультациям',
    close: 'Закрыть',
    existingConsultationMessage: 'У вас уже существует активная консультация с врачом',
    goToHistoryToContact: 'Вы можете перейти к истории консультаций, чтобы продолжить общение в существующей консультации.',
    format: 'Формат',
    chatConsultation: 'Консультация в чате',
    messageLimit: 'Лимит сообщений',
    messageCountInfo: '30 сообщений (с возможностью продления)',
    noteToDoctor: 'Примечание для врача (необязательно)',
    notePlaceholder: 'Опишите ваши симптомы или вопросы, которые хотели бы обсудить с врачом...',
    send: 'Отправить',
    
    // Переводы для DoctorApplicationForm
    doctorApplicationTitle: 'Заявка на роль врача',
    doctorApplicationDescription: 'Заполните все поля формы для подачи заявки на получение роли врача на платформе',
    yourPhoto: 'Ваша фотография',
    uploadPhoto: 'Загрузить фото',
    photoRequirements: 'Загрузите профессиональную фотографию в формате JPG или PNG, не более 5 МБ',
    diplomaCertificate: 'Диплом/Сертификат об образовании',
    uploadDiploma: 'Загрузить диплом',
    diplomaRequirements: 'Загрузите скан диплома или сертификата в формате PDF, JPG или PNG, не более 10 МБ',
    license: 'Лицензия/Сертификат для практики',
    uploadLicense: 'Загрузить лицензию',
    licenseRequirements: 'Загрузите скан лицензии или сертификата в формате PDF, JPG или PNG, не более 10 МБ',
    consultationLanguages: 'Языки консультаций',
    selectLanguages: 'Выберите языки, на которых вы проводите консультации',
    practiceRegion: 'Регион практики',
    practiceDistrict: 'Район практики',
    additionalInformation: 'Дополнительная информация',
    additionalInfoPlaceholder: 'Укажите дополнительную информацию о своей практике, достижениях или специализации...',
    submitApplication: 'Отправить заявку',
    applicationSubmitted: 'Заявка успешно отправлена',
    applicationSubmittedMessage: 'Ваша заявка была успешно отправлена и будет рассмотрена администратором в ближайшее время.',
    backToProfile: 'Вернуться к профилю',
    fieldsRequiredInfo: 'Все поля, отмеченные *, являются обязательными для заполнения',
    validationErrors: {
      fullNameRequired: 'Пожалуйста, укажите ваше полное имя',
      specializationRequired: 'Пожалуйста, укажите вашу специализацию',
      experienceRequired: 'Пожалуйста, укажите ваш опыт работы',
      educationRequired: 'Пожалуйста, укажите ваше образование',
      licenseNumberRequired: 'Пожалуйста, укажите номер вашей лицензии/сертификата',
      cityRequired: 'Пожалуйста, выберите город/регион вашей практики',
      districtRequired: 'Пожалуйста, укажите район вашей практики',
      languagesRequired: 'Пожалуйста, выберите языки консультаций',
      photoRequired: 'Пожалуйста, загрузите вашу фотографию',
      diplomaRequired: 'Пожалуйста, загрузите скан вашего диплома',
      licenseFileRequired: 'Пожалуйста, загрузите скан вашей лицензии/сертификата'
    },
    
    // Переводы для AdminLoginPage
    adminLogin: 'Вход для администраторов',
    accessForAuthorizedOnly: 'Доступ только для авторизованных сотрудников',
    adminEmail: 'Email администратора',
    enterEmail: 'Введите email',
    enterPassword: 'Введите пароль',
    loginToSystem: 'Войти в систему',
    testLogin: 'Вход для тестирования',
    accessCheckingTitle: 'Проверка доступа',
    noAdminRights: 'У вас нет прав администратора',
    pleaseCompleteAllFields: 'Пожалуйста, заполните все поля',
    loginError: 'Ошибка входа',
    medicalPlatformAdminPanel: 'Панель администрирования медицинской платформы',
    accessOnlyForSoglomAdmins: 'Доступ только для администраторов Soglom'
    },
    uz: {
    selectLanguage: 'Tilni tanlang',
    language: 'Til',
    home: 'Bosh sahifa',
    findDoctor: 'Shifokor topish',
    history: 'Tarix',
    profile: 'Profil',
    logout: 'Chiqish',
    login: 'Kirish',
    register: 'Ro\'yxatdan o\'tish',
    search: 'Qidiruv',
    specialization: 'Mutaxassislik',
    city: 'Shahar',
    country: 'Mamlakat',
    price: 'Narx',
    verifiedDoctor: 'Tasdiqlangan shifokor',
    experience: 'Ish tajribasi',
    organization: 'Tashkilot',
    position: 'Lavozim',
    years: 'Ish yillari',
    languages: 'Tillar',
    consultation: 'Konsultatsiya',
    reviews: 'Sharhlar',
    rating: 'Reyting',
    about: 'Shifokor haqida',
    education: 'Ta\'lim',
    workExperience: 'Ish tajribasi',
    cost: 'Konsultatsiya narxi',
    loading: 'Yuklanmoqda...',
    noResults: 'Natijalar topilmadi',
    error: 'Xatolik yuz berdi',
    patient: 'Bemor',
    doctor: 'Shifokor',
    admin: 'Administrator',
    user: 'Foydalanuvchi',
    notifications: 'Bildirishnomalar',
    markAllRead: 'Barchasini o\'qilgan deb belgilash',
    newNotification: 'Yangi',
    expand: 'Batafsil',
    collapse: 'Yig\'ish',
    profileSettings: 'Profil sozlamalari',
    adminPanel: 'Admin panel',
    selectSpecialization: 'Mutaxassislikni tanlang',
    allSpecializations: 'Barcha mutaxassisliklar',
    selectCity: 'Shaharni tanlang',
    allCities: 'Barcha shaharlar',
    selectLanguage: 'Tilni tanlang',
    allLanguages: 'Barcha tillar',
    searching: 'Qidirmoqda...',
    location: 'Joylashuv',
    notSpecified: 'Ko\'rsatilmagan',
    organizations: 'tashkilotlar',
    languages: 'Muloqot tillari:',
    emailRequired: 'Iltimos, emailni kiriting',
    passwordRequired: 'Iltimos, parolni kiriting',
    invalidEmail: 'Iltimos, to\'g\'ri email kiriting',
    loginError: 'Kirishda xato yuz berdi. Keyinroq urinib ko\'ring.',
    emailPlaceholder: 'Emailingizni kiriting',
    passwordPlaceholder: 'Parolingizni kiriting',
    currentPasswordRequired: 'Iltimos, hozirgi parolni kiriting',
    newPasswordRequired: 'Iltimos, yangi parolni kiriting',
    passwordMinLength: 'Yangi parol kamida 8 belgidan iborat bo\'lishi kerak',
    passwordMismatch: 'Parollar mos kelmaydi',
    passwordSameAsCurrent: 'Yangi parol hozirgi paroldan farqli bo\'lishi kerak',
    securityError: 'Xavfsizlik xatosi. Sahifani yangilang va qayta urinib ko\'ring.',
    changePhoto: 'Rasmni o\'zgartirish',
    saveChanges: 'O\'zgarishlarni saqlash',
    currentPassword: 'Hozirgi parol',
    newPassword: 'Yangi parol',
    confirmPassword: 'Parolni tasdiqlash',
    practiceDistrict: 'Amaliyot hududi',
    workExperience: 'Ish tajribasi (yil)',
    cityRegion: 'Shahar/Viloyat',
    password: 'Parol',
    rememberMe: 'Meni eslash',
    forgotPassword: 'Parolni unutdingizmi?',
    noAccount: 'Akkauntingiz yo\'qmi?',
    phoneNumber: 'Telefon raqami',
    fullNameRequired: 'Iltimos, to\'liq ismingizni kiriting',
    phoneRequired: 'Iltimos, telefon raqamini kiriting',
    cityRegionRequired: 'Iltimos, shahar/viloyatni tanlang',
    districtRequired: 'Iltimos, hududni tanlang',
    confirmPasswordRequired: 'Iltimos, parolni tasdiqlang',
    passwordMinimum: 'Parol kamida 8 belgidan iborat bo\'lishi kerak',
    termsRequired: 'Ro\'yxatdan o\'tish uchun foydalanish shartlariga rozilik berish kerak',
    registrationError: 'Ro\'yxatdan o\'tishda xato. Keyinroq urinib ko\'ring.',
    registrationSuccess: 'Ro\'yxatdan o\'tish muvaffaqiyatli!',
    verificationEmailSent: 'Tasdiqlash xati yuborildi:',
    verificationInstructions: 'Emailingizni tekshiring va akkauntni faollashtirish uchun xatdagi havolaga o\'ting.',
    goToLogin: 'Kirish sahifasiga o\'tish',
    accountCreatedSuccess: 'Akkauntingiz muvaffaqiyatli yaratildi. Endi ko\'rsatilgan ma\'lumotlar bilan tizimga kirishingiz mumkin.',
    noVerificationEmail: 'Xat kelmadimi? "Spam" papkasini tekshiring yoki',
    resendEmail: 'qayta jo\'natish',
    basicInfo: 'Asosiy ma\'lumotlar',
    securityInfo: 'Xavfsizlik',
    locationInfo: 'Manzil',
    additionalInfo: 'Qo\'shimcha ma\'lumotlar',
    agreeToTerms: 'Men roziman',
    termsOfService: 'foydalanish shartlari',
    and: 'va',
    privacyPolicy: 'maxfiylik siyosati',
    createAccount: 'Akkount yaratish',
    haveAccount: 'Akkauntingiz bormi?',
    platformDescription: 'Eng yaxshi mutaxassislar bilan onlayn konsultatsiya uchun tibbiy platforma',
    alreadyGoogleRegistered: 'Google orqali ro\'yxatdan o\'tganmisiz?',
    loginWithGoogle: 'Google orqali kirish',
    or: 'Yoki',
    loginRegister: 'Kirish, ro\'yxatdan o\'tish',
    platformAdvantages: 'Platformamizning afzalliklari:',
    convenientDoctorSearch: 'Mutaxassislik bo\'yicha shifokorlarni qulay qidirish',
    onlineConsultationsAnywhere: 'Dunyoning istalgan nuqtasidan onlayn konsultatsiya',
    secureDataExchange: 'Tibbiy ma\'lumotlarni himoyalangan almashish',
    needHelp: 'Yordam kerakmi?',
    contactUs: 'Biz bilan bog\'laning',
    enterFullName: 'To\'liq ismingizni kiriting',
    enterEmail: 'Emailingizni kiriting',
    enterPhoneNumber: 'Telefon raqamingizni kiriting',
    enterPassword: 'Parolni kiriting',
    enterConfirmPassword: 'Parolni tasdiqlang',
    selectCityRegion: 'Shahar yoki viloyatingizni tanlang',
    selectDistrict: 'Hududingizni tanlang',
    enterAddress: 'Manzilingizni kiriting',
    loginSystemAccess: 'Tibbiy konsultatsiyalarga kirish uchun tizimga kiring',
    createNewAccount: 'Yangi akkount yaratish',
    adminAccess: 'Administratorlar uchun kirish',
    registerForConsultations: 'Mutaxassislardan konsultatsiya olish uchun ro\'yxatdan o\'ting',
    loginTab: 'Kirish',
    registerTab: 'Ro\'yxatdan o\'tish',
    googleLogin: 'Google orqali kirish',
    googleLoginHint: 'Agar Google orqali ro\'yxatdan o\'tgan bo\'lsangiz, iltimos quyidagi tugmani ishlating',
    belowText: 'pastda.',
    googleLoginTooltip: 'Agar Google orqali ro\'yxatdan o\'tgan bo\'lsangiz, yuqoridagi \'Google orqali kirish\' tugmasini ishlating',
    medicalInfoPlaceholder: 'Surunkali kasalliklar, allergiyalar va hokazo haqida ma\'lumot kiriting',
    agreeWith: 'Men roziman',
    registerButton: 'Ro\'yxatdan o\'tish',
    alreadyHaveAccount: 'Akkauntingiz bormi?',
    loginLink: 'Kirish',
    minimumChars: 'Kamida 8 ta belgi',
    repeatPassword: 'Parolni takrorlang',
    passwordsDontMatch: 'Parollar mos kelmaydi',
    // Дополнительные переводы
    welcome: 'Soglom\'ga xush kelibsiz',
    subtitle: 'Sizning raqamli sog\'liqni saqlash yordamchingiz',
    getStarted: 'Boshlash',
    howItWorks: 'Qanday ishlaydi',
    findDoctors: 'Shifokorlarni topish',
    bookAppointment: 'Qabulga yozilish',
    consultOnline: 'Onlayn maslahat',
    step: 'Qadam',
    chooseDoctor: 'Shifokorni tanlang',
    chooseDoctorDesc: 'Tasdiqlangan shifokorlarimiz orasidan mos mutaxassisni toping',
    scheduleAppointment: 'Uchrashuvni rejalashtiring',
    scheduleAppointmentDesc: 'Konsultatsiya uchun qulay vaqtni tanlang',
    getConsultation: 'Konsultatsiya oling',
    getConsultationDesc: 'Onlayn yoki oflayn sifatli tibbiy yordam oling',
    verifiedDoctors: 'Tasdiqlangan shifokorlar',
    onlineConsultations: 'Onlayn konsultatsiyalar',
    securePayments: 'Xavfsiz to\'lovlar',
    featuredDoctors: 'Tavsiya etilgan shifokorlar',
    viewProfile: 'Profilni ko\'rish',
    becomeDoctor: 'Shifokor bo\'lish',
    moreDetails: 'Batafsil',
    bookNow: 'Yozilish',
    fullName: 'To\'liq ism',
    contactPhone: 'Aloqa telefoni',
    address: 'Manzil',
    district: 'Tuman',
    medicalInfo: 'Tibbiy ma\'lumot',
    editProfile: 'Profilni tahrirlash',
    profileInfo: 'Profil ma\'lumotlari',
    save: 'Saqlash',
    cancel: 'Bekor qilish',
    required: 'Majburiy maydon',
    phoneInvalid: 'Telefon raqami formati noto\'g\'ri',
    profileSaved: 'Profil muvaffaqiyatli saqlandi!',
    profileNotCreated: 'Profil hali yaratilmagan. Iltimos, ma\'lumotlarni to\'ldiring.',
    pleaseCompleteBefore: 'Iltimos, quyidagi ma\'lumotlarni to\'ldiring.',
    settings: 'Sozlamalar',
    changePassword: 'Parolni o\'zgartirish',
    updatePasswordSecurity: 'Xavfsizlik uchun parolni yangilang',
    notificationSettings: 'Bildirishnoma sozlamalari',
    manageNotifications: 'Bildirishnomalarni boshqarish',
    deleteAccount: 'Hisobni o\'chirish',
    deleteAccountPermanently: 'Hisobni butunlay o\'chirish',
    security: 'Xavfsizlik',
    passwordSecuritySettings: 'Hisobingizning parol va xavfsizlik sozlamalarini boshqarish',
    
    // Сообщения об авторизации и успешных операциях
    authSuccess: 'Avtorizatsiya muvaffaqiyatli!',
    authProcessing: 'Avtorizatsiyani yakunlash...',
    authProcessingDescription: 'Iltimos, kuting, biz sizning Google orqali avtorizatsiyangizni qayta ishlamoqdamiz.',
    authErrorTitle: 'Avtorizatsiya xatosi',
    authRedirectMessage: 'Siz bosh sahifaga yo\'naltirilasiz...',
    returnToLogin: 'Kirish sahifasiga qaytish',
    consultationStarted: 'Konsultatsiya muvaffaqiyatli boshlandi',
    thanksForReview: 'Fikr-mulohazangiz uchun rahmat!',
    redirectingHome: 'Bosh sahifaga yo\'naltirish...',
    emailVerified: 'Email muvaffaqiyatli tasdiqlandi!',
    emailAlreadyVerified: 'Email allaqachon muvaffaqiyatli tasdiqlangan! Profilga o\'tmoqdamiz...',
    newVerificationSent: 'Tasdiqlash uchun yangi havola ko\'rsatilgan pochtaga yuborildi',
    emailAlreadyConfirmed: 'allaqachon tasdiqlangan. Xush kelibsiz!',
    emailSuccessfullyVerified: 'Email muvaffaqiyatli tasdiqlandi. Xush kelibsiz!',
    profileCreatedFromRegistration: 'Profil ro\'yxatdan o\'tish ma\'lumotlari bilan muvaffaqiyatli yaratildi!',
    consultationRequestSent: 'Konsultatsiya so\'rovi muvaffaqiyatli yuborildi!',
    pushNotificationsEnabled: 'Push-bildirishnomalar yoqildi!',
    passwordChanged: 'Parol muvaffaqiyatli o\'zgartirildi',
    profilePhotoUpdated: 'Profil rasmi muvaffaqiyatli yangilandi',
    notificationSettingsSaved: 'Bildirishnoma sozlamalari saqlandi',
    accountDeleted: 'Hisob muvaffaqiyatli o\'chirildi',
    reviewAlreadySent: 'Sharh allaqachon yuborilgan',
    reviewSent: 'Sharh muvaffaqiyatli yuborildi',
    avatarUpdated: 'Avatar muvaffaqiyatli yangilandi',
    consultationCompleted: 'Konsultatsiya muvaffaqiyatli yakunlandi',
    consultationAutoCompleted: 'Xabarlar limitiga yetganligi sababli konsultatsiya avtomatik yakunlandi',
    
    // Дополнительные переводы для Google авторизации  
    attention: 'Diqqat',
    extensionWarning: 'Avtorizatsiya jarayoniga xalaqit berishi mumkin bo\'lgan brauzer kengaytmalari aniqlandi. Agar muammolar yuzaga kelsa, kengaytmalarni vaqtincha o\'chiring yoki inkognito rejimidan foydalaning.',
    authErrorCodeExpired: 'Avtorizatsiya kodi muddati tugagan yoki noto\'g\'ri. Iltimos, qayta kirish urinib ko\'ring.',
    authErrorCodeUsed: 'Bu avtorizatsiya kodi allaqachon ishlatilgan. Iltimos, qayta kiring.',
    authErrorGeneric: 'Google orqali avtorizatsiya qilishda xatolik yuz berdi. Iltimos, qayta urinib ko\'ring.',
    
    // Qo'shimcha tizim xabarlari
    connectionLost: 'Server bilan aloqa uzildi. Keyinroq urinib ko\'ring.',
    messageSendFailed: 'Xabarni yuborib bo\'lmadi. Qayta urinib ko\'ring.',
    connectionError: 'Server bilan aloqa o\'rnatib bo\'lmadi.',
    chatLoadError: 'Chatni yuklashda xatolik. Sahifani yangilang.',
    serverConnectionFailed: 'Serverga ulanib bo\'lmadi',
    connectingToServer: 'Serverga ulanmoqda...',
    finalizingConsultation: 'Konsultatsiya yakunlanmoqda...',
    consultationCompletedSuccess: 'Konsultatsiya muvaffaqiyatli yakunlandi',
    completionFailed: 'Konsultatsiyani yakunlab bo\'lmadi. Sahifani yangilab qayta urinib ko\'ring.',
    autoCompletionFailed: 'Konsultatsiyani avtomatik yakunlab bo\'lmadi. Shifokorga murojaat qiling.',
    messageLimitReached: 'Xabarlar chegarasiga yetdi. Konsultatsiya yakunlanadi.',
    messageLimitAutoComplete: 'Xabarlar chegarasiga yetganligi sababli konsultatsiya avtomatik yakunlandi',
    connectionTimeout: 'Ulanish urinishlar soni oshib ketdi. Sahifani yangilang.',
    unknownError: 'Noma\'lum xatolik yuz berdi',
    statusActive: 'Faol',
    statusCompleted: 'Yakunlangan',
    statusWaiting: 'Kutilmoqda',
    startChatMessage: 'Birinchi xabar yuborib suhbatni boshlang',
    waitForStart: 'Konsultatsiya boshlanishini kuting',
    reviewFormError: 'Sharh formasini ochib bo\'lmadi',
    messagePlaceholder: 'Xabar kiriting...',
    sendingDisabled: 'Xabar yuborish mumkin emas',
    messageLimitReachedStatus: 'Xabarlar chegarasiga yetdi',
    refreshChat: 'Chatni yangilash',
    loadingMessages: 'Xabarlar yuklanmoqda...',
    finishConsultation: 'Konsultatsiyani yakunlash',
    noMessages: 'Xabarlar yo\'q',
    startConversation: 'Birinchi xabar yuborib suhbatni boshlang',
    waitForConsultation: 'Konsultatsiya boshlanishini kuting',
    messagingDisabled: 'Xabar yuborish mumkin emas',
    enterMessage: 'Xabar kiriting...',
    messageLimitExceeded: 'Siz ushbu konsultatsiya uchun xabarlar chegarasiga yetdingiz',
    completeConsultation: 'Konsultatsiyani yakunlash',
    confirmCompleteConsultation: 'Konsultatsiyani yakunlashni hohlaysizmi? Yakunlanganidan so\'ng xabar yuborish mumkin bo\'lmaydi.',
    patientCanLeaveReview: 'Bemor konsultatsiya haqida sharh qoldirish imkoniga ega bo\'ladi.',
    
    // Переводы для ReviewForm
    leaveReview: 'Sharh qoldirish',
    consultationWith: 'Konsultatsiya bilan',
    reviewHelpMessage: 'Sizning sharhingiz boshqa bemorlarga mos shifokorni tanlashda yordam beradi. Fikr-mulohaza uchun rahmat!',
    rateConsultation: 'Konsultatsiyani qanday baholaysiz?',
    ratingVeryBad: 'Juda yomon',
    ratingBad: 'Yomon',
    ratingNormal: 'Oddiy',
    ratingGood: 'Yaxshi',
    ratingExcellent: 'A\'lo',
    yourComment: 'Sizning izohingiz',
    reviewCommentPlaceholder: 'Konsultatsiya tajribangiz haqida gapirib bering...',
    commentHelpText: 'Sizning izohingiz shifokorga konsultatsiya sifatini yaxshilashda yordam beradi',
    submitReview: 'Sharh yuborish',
    reviewSubmitError: 'Sharhni yuborib bo\'lmadi. Keyinroq urinib ko\'ring.',
    
    // Переводы для DoctorProfilePage
    bookConsultation: 'Konsultatsiyaga yozilish',
    doctorInfo: 'Shifokor haqida ma\'lumot',
    practiceLocation: 'Amaliyot joylashuvi',
    specializations: 'Mutaxassisliklar',
    consultationLanguages: 'Konsultatsiya tillari',
    doctorReviews: 'Shifokor haqida sharhlar',
    reviewWithoutComment: 'Izohsiz sharh',
    doctorPracticeRegion: 'Shifokor amaliyot hududi',
    noDoctorReviews: 'Bu shifokor haqida hali sharhlar yo\'q',
    beFirstToReview: 'Konsultatsiyadan keyin sharh qoldirgan birinchi kishi bo\'ling',
    
    // Переводы для SearchDoctorsPage
    findSpecialistDescription: 'Konsultatsiya uchun mos mutaxassisni toping',
    searchInRegion: 'Hududda qidiruv',
    autoFilterByRegion: 'Shifokorlar sizning hududingiz bo\'yicha avtomatik filtrlandi. Profil sozlamalarida o\'zgartirish mumkin.',
    doctorsFound: 'Shifokorlar topildi',
    searchResults: 'Qidiruv natijalari',
    page: 'Sahifa',
    of: 'dan',
    noDoctorsFound: 'Qidiruv mezonlaringizga mos shifokorlar topilmadi',
    tryChangeSearchParams: 'Qidiruv parametrlarini o\'zgartirib ko\'ring yoki boshqa mutaxassislikni tanlang',
    
    // Переводы для HomePage
    findDoctorDescription: 'Mutaxassislik bo\'yicha shifokorlarni qidirish va konsultatsiyaga yozilish',
    historyDescription: 'Konsultatsiyalar va to\'lovlar tarixini ko\'rish',
    profileSettingsDescription: 'Shaxsiy ma\'lumotlarni yangilash va hisob sozlamalari',
    myConsultations: 'Mening konsultatsiyalarim',
    myConsultationsDescription: 'Joriy va kelgusi konsultatsiyalarni boshqarish',
    doctorProfileDescription: 'Professional ma\'lumotlar va jadvallarni yangilash',
    analytics: 'Analitika',
    analyticsDescription: 'Konsultatsiya statistikasi va bemorlar sharhlari',
    doctorWelcomeMessage: 'Bu yerda siz konsultatsiyalarni boshqarishingiz va profilingizni sozlashingiz mumkin.',
    patientWelcomeMessage: 'Bu yerda siz shifokorlarni qidirishingiz, konsultatsiyalarni boshqarishingiz va tarixni ko\'rishingiz mumkin.',
    emailVerificationRequired: 'Email tasdiqlash talab qilinadi',
    emailVerificationMessage: 'Emailingizni tasdiqlamaguncha platformaning to\'liq funksionalligidan foydalana olmaysiz. Iltimos, pochtangizni tekshiring va xatdagi havolaga o\'ting.',
    havingProblems: 'Muammolar bormi?',
    goTo: 'O\'tish',
    goToAdminPanel: 'Admin-panelga o\'tish',
    contactSupport: 'Qo\'llab-quvvatlash bilan bog\'lanish',
    systemManagement: 'Tizim va foydalanuvchilarni boshqarish',
    adminPanelDescription: 'Foydalanuvchilar va shifokor arizalarini boshqarish',
    systemAnalytics: 'Tizim analitikasi',
    platformUsageStats: 'Platforma foydalanish statistikasi',
    featureInDevelopment: 'Funksional ishlab chiqilmoqda',
        inDevelopment: 'Ishlab chiqilmoqda',
    
    // Переводы для AdminPage
    adminPanelTitle: 'Administrator paneli',
    systemUserManagement: 'Tizim va foydalanuvchilarni boshqarish',
    administrativePanel: 'Ma\'muriy panel',
    account: 'Hisob',
    role: 'Rol',
    administrator: 'Administrator',
    doctorApplications: 'Shifokor arizalari',
    doctorRoleApplications: 'Shifokor roli uchun arizalar',
    pending: 'Kutilmoqda',
    approved: 'Tasdiqlangan',
    rejected: 'Rad etilgan',
    all: 'Barchasi',
    users: 'Foydalanuvchilar',
    userManagement: 'Foydalanuvchilarni boshqarish',
    refreshList: 'Ro\'yxatni yangilash',
    noUsersInSystem: 'Tizimda foydalanuvchilar yo\'q',
    notifications: 'Bildirishnomalar',
    notificationManagement: 'Bildirishnomalarni boshqarish',
    browserPushStatus: 'Brauzer push-bildirishnomalar holati',
    browserSupport: 'Brauzer qo\'llab-quvvatlashi',
    supported: 'Qo\'llab-quvvatlanadi',
    notSupported: 'Qo\'llab-quvvatlanmaydi',
    permission: 'Ruxsat',
    allowed: 'Ruxsat berilgan',
    blocked: 'Bloklangan',
    notDetermined: 'Aniqlanmagan',
    requestPermission: 'Ruxsat so\'rash',
    testBrowserNotifications: 'Brauzer bildirishnomalarini sinash',
    notificationTitle: 'Bildirishnoma sarlavhasi',
    notificationText: 'Bildirishnoma matni',
    notificationType: 'Bildirishnoma turi',
    system: 'Tizim',
    consultation: 'Konsultatsiya',
    appointment: 'Yozilish',
    message: 'Xabar',
    update: 'Yangilanish',
    recipientParams: 'Qabul qiluvchi parametrlari',
    sendToAll: 'Barcha foydalanuvchilarga',
    sendByRole: 'Foydalanuvchi roliga ko\'ra',
    sendToSpecific: 'Aniq foydalanuvchiga',
    selectRole: 'Rolni tanlang',
    userIdForNotification: 'Bildirishnoma uchun foydalanuvchi ID',
    sendNotification: 'Bildirishnoma yuborish',
    sendWebSocketNotifications: 'WebSocket bildirishnomalarini yuborish',
    personalData: 'Shaxsiy ma\'lumotlar',
    fullName: 'To\'liq ism',
    phoneNumber: 'Telefon raqam',
    role: 'Rol',
    registrationDate: 'Ro\'yxatdan o\'tish sanasi',
    specialization: 'Mutaxassislik',
    changeRole: 'Rolni o\'zgartirish',
    newRole: 'Yangi rol',
    
    // Статусы консультаций
    completed: 'Tugallangan',
    active: 'Faol',
    pending: 'Kutilmoqda',
    cancelled: 'Bekor qilingan',
    unknown: 'Noma\'lum',
    
    // Дополнительные переводы для HistoryPage
    doctor: 'Shifokor',
    patient: 'Bemor',
    status: 'Holat',
    creationDate: 'Yaratilgan sana',
    startTime: 'Boshlangan vaqt',
    noConsultationsHistory: 'Sizda hali konsultatsiyalar tarixi yo\'q',
    loadingHistory: 'Tarix yuklanmoqda...',
    failedToLoadHistory: 'Konsultatsiyalar tarixini yuklab bo\'lmadi. Iltimos, keyinroq urinib ko\'ring.',
    failedToLoadUnreadMessages: 'O\'qilmagan xabarlarni yuklab bo\'lmadi, keshirlangan ma\'lumotlardan foydalanilmoqda',
    
    // Переводы для PatientProfileForm
    consultationHistoryWillBeUnavailable: 'Konsultatsiyalar tarixi mavjud bo\'lmaydi',
    editProfile: 'Profilni tahrirlash',
    saveProfile: 'Profilni saqlash',
    cancelEditing: 'Tahrirni bekor qilish',
    changePassword: 'Parolni o\'zgartirish',
    notificationSettings: 'Bildirishnoma sozlamalari',
    privacySettings: 'Maxfiylik sozlamalari',
    deleteAccount: 'Hisobni o\'chirish',
    currentPassword: 'Joriy parol',
    newPassword: 'Yangi parol',
    confirmPassword: 'Parolni tasdiqlang',
    emailNotifications: 'Email bildirishnomalar',
    pushNotifications: 'Push bildirishnomalar',
    appointmentReminders: 'Yozilish eslatmalari',
    medicalInfo: 'Tibbiy ma\'lumotlar',
    medicalInfoPlaceholder: 'Surunkali kasalliklar, allergiyalar, qabul qilinadigan dorilar...',
    profileImageUpload: 'Profil rasmini yuklash',
    selectPhoto: 'Rasm tanlang',
    changePhoto: 'Rasmni o\'zgartirish',
    profileSaved: 'Profil saqlandi',
    profileSaveError: 'Profilni saqlashda xatolik',
    passwordChanged: 'Parol o\'zgartirildi',
    passwordChangeError: 'Parolni o\'zgartirishda xatolik',
    notificationSettingsUpdated: 'Bildirishnoma sozlamalari yangilandi',
    deleteAccountConfirmation: 'Hisobni o\'chirishni xohlaysizmi?',
    thisActionCannotBeUndone: 'Bu amalni qaytarib bo\'lmaydi',
    selectRegion: 'Viloyatni tanlang',
    selectDistrict: 'Tumanni tanlang',
    
    // Переводы для RequestConsultationModal
    youAlreadyHaveConsultation: 'Sizda allaqachon konsultatsiya bor',
    consultationApplication: 'Konsultatsiya uchun ariza',
    consultationRequestSent: 'Konsultatsiya uchun ariza yuborildi',
    consultationRequestError: 'Konsultatsiya arizasini yuborishda xatolik',
    consultationAlreadyActive: 'Sizda bu shifokor bilan allaqachon faol konsultatsiya bor',
    goToConsultations: 'Konsultatsiyalarga o\'tish',
    close: 'Yopish',
    existingConsultationMessage: 'Sizda shifokor bilan allaqachon faol konsultatsiya mavjud',
    goToHistoryToContact: 'Mavjud konsultatsiyada muloqotni davom ettirish uchun konsultatsiyalar tarixiga o\'tishingiz mumkin.',
    format: 'Format',
    chatConsultation: 'Chatda konsultatsiya',
    messageLimit: 'Xabarlar chegarasi',
    messageCountInfo: '30 ta xabar (uzaytirish imkoniyati bilan)',
    noteToDoctor: 'Shifokor uchun izoh (ixtiyoriy)',
    notePlaceholder: 'Shifokor bilan muhokama qilmoqchi bo\'lgan alomatlar yoki savollaringizni tasvirlab bering...',
    send: 'Yuborish'
    },
    en: {
    selectLanguage: 'Select language',
    language: 'Language',
    home: 'Home',
    findDoctor: 'Find Doctor',
    history: 'History',
    profile: 'Profile',
    logout: 'Logout',
    login: 'Login',
    register: 'Register',
    search: 'Search',
    specialization: 'Specialization',
    city: 'City',
    country: 'Country',
    price: 'Price',
    verifiedDoctor: 'Verified Doctor',
    experience: 'Experience',
    organization: 'Organization',
    position: 'Position',
    years: 'Years of work',
    languages: 'Languages',
    consultation: 'Consultation',
    reviews: 'Reviews',
    rating: 'Rating',
    about: 'About doctor',
    education: 'Education',
    workExperience: 'Work Experience',
    cost: 'Consultation cost',
    loading: 'Loading...',
    noResults: 'No results found',
    error: 'An error occurred',
    patient: 'Patient',
    doctor: 'Doctor',
    admin: 'Administrator',
    user: 'User',
    notifications: 'Notifications',
    markAllRead: 'Mark all as read',
    newNotification: 'New',
    expand: 'Show more',
    collapse: 'Show less',
    profileSettings: 'Profile Settings',
    adminPanel: 'Admin Panel',
    selectSpecialization: 'Select specialization',
    allSpecializations: 'All specializations',
    selectCity: 'Select city',
    allCities: 'All cities',
    selectLanguage: 'Select language',
    allLanguages: 'All languages',
    searching: 'Searching...',
    location: 'Location',
    notSpecified: 'Not specified',
    organizations: 'organizations',
    languages: 'Languages:',
    emailRequired: 'Please enter your email',
    passwordRequired: 'Please enter your password',
    invalidEmail: 'Please enter a valid email',
    loginError: 'Login error occurred. Please try again later.',
    emailPlaceholder: 'Enter your email',
    passwordPlaceholder: 'Enter your password',
    currentPasswordRequired: 'Please enter current password',
    newPasswordRequired: 'Please enter new password',
    passwordMinLength: 'New password must contain at least 8 characters',
    passwordMismatch: 'Passwords do not match',
    passwordSameAsCurrent: 'New password must be different from current',
    securityError: 'Security error. Please refresh page and try again.',
    changePhoto: 'Change Photo',
    saveChanges: 'Save Changes',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    practiceDistrict: 'Practice District',
    workExperience: 'Work Experience (years)',
    cityRegion: 'City/Region',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    noAccount: 'Don\'t have an account?',
    phoneNumber: 'Phone Number',
    fullNameRequired: 'Please enter your full name',
    phoneRequired: 'Please enter your phone number',
    cityRegionRequired: 'Please select a city/region',
    districtRequired: 'Please select a district',
    confirmPasswordRequired: 'Please confirm your password',
    passwordMinimum: 'Password must be at least 8 characters long',
    termsRequired: 'You must agree to the terms of service to register',
    registrationError: 'Registration error. Please try again later.',
    registrationSuccess: 'Registration successful!',
    verificationEmailSent: 'We sent a verification email to',
    verificationInstructions: 'Please check your email and click the link in the email to activate your account.',
    goToLogin: 'Go to login page',
    accountCreatedSuccess: 'Your account has been successfully created. You can now log in using the provided credentials.',
    noVerificationEmail: 'Didn\'t receive the email? Check your "Spam" folder or',
    resendEmail: 'resend',
    basicInfo: 'Basic Information',
    securityInfo: 'Security',
    locationInfo: 'Location',
    additionalInfo: 'Additional Information',
    agreeToTerms: 'I agree to the',
    termsOfService: 'terms of service',
    and: 'and',
    privacyPolicy: 'privacy policy',
    createAccount: 'Create Account',
    haveAccount: 'Already have an account?',
    platformDescription: 'Medical platform for online consultations with the best specialists',
    alreadyGoogleRegistered: 'Already registered through Google?',
    loginWithGoogle: 'Login with Google',
    or: 'Or',
    loginRegister: 'Login, registration',
    platformAdvantages: 'Our platform advantages:',
    convenientDoctorSearch: 'Convenient doctor search by specialization',
    onlineConsultationsAnywhere: 'Online consultations from anywhere in the world',
    secureDataExchange: 'Secure medical data exchange',
    needHelp: 'Need help?',
    contactUs: 'Contact us',
    enterFullName: 'Enter your full name',
    enterEmail: 'Enter your email',
    enterPhoneNumber: 'Enter your phone number',
    enterPassword: 'Enter password',
    enterConfirmPassword: 'Confirm password',
    selectCityRegion: 'Select your city or region',
    selectDistrict: 'Select your district',
    enterAddress: 'Enter your address',
    loginSystemAccess: 'Log in to access medical consultations',
    createNewAccount: 'Create new account',
    adminAccess: 'Administrator login',
    registerForConsultations: 'Register to get consultations from specialists',
    loginTab: 'Login',
    registerTab: 'Registration',
    googleLogin: 'Login with Google',
    googleLoginHint: 'If you registered through Google, please use the button',
    belowText: 'below.',
    googleLoginTooltip: 'If you registered through Google, use the \'Login with Google\' button above',
    medicalInfoPlaceholder: 'Enter information about chronic diseases, allergies, etc.',
    agreeWith: 'I agree with',
    registerButton: 'Register',
    alreadyHaveAccount: 'Already have an account?',
    loginLink: 'Login',
    minimumChars: 'Minimum 8 characters',
    repeatPassword: 'Repeat password',
    passwordsDontMatch: 'Passwords do not match',
    // Additional translations
    welcome: 'Welcome to Soglom',
    subtitle: 'Your digital healthcare assistant',
    getStarted: 'Get Started',
    howItWorks: 'How it works',
    findDoctors: 'Find Doctors',
    bookAppointment: 'Book Appointment',
    consultOnline: 'Consult Online',
    step: 'Step',
    chooseDoctor: 'Choose Doctor',
    chooseDoctorDesc: 'Find the right specialist among our verified doctors',
    scheduleAppointment: 'Schedule Appointment',
    scheduleAppointmentDesc: 'Choose a convenient time for consultation',
    getConsultation: 'Get Consultation',
    getConsultationDesc: 'Receive quality medical care online or offline',
    verifiedDoctors: 'Verified Doctors',
    onlineConsultations: 'Online Consultations',
    securePayments: 'Secure Payments',
    featuredDoctors: 'Featured Doctors',
    viewProfile: 'View Profile',
    becomeDoctor: 'Become a Doctor',
    moreDetails: 'More Details',
    bookNow: 'Book Now',
    fullName: 'Full Name',
    contactPhone: 'Contact Phone',
    address: 'Address',
    district: 'District',
    medicalInfo: 'Medical Information',
    editProfile: 'Edit Profile',
    profileInfo: 'Profile Information',
    save: 'Save',
    cancel: 'Cancel',
    required: 'Required field',
    phoneInvalid: 'Invalid phone number format',
    profileSaved: 'Profile saved successfully!',
    profileNotCreated: 'Profile not created yet. Please fill in the information.',
    pleaseCompleteBefore: 'Please complete the information below.',
    settings: 'Settings',
    changePassword: 'Change Password',
    updatePasswordSecurity: 'Update password for security',
    notificationSettings: 'Notification Settings',
    manageNotifications: 'Manage notifications',
    deleteAccount: 'Delete Account',
    deleteAccountPermanently: 'Delete account permanently',
    security: 'Security',
    passwordSecuritySettings: 'Manage password and security settings of your account',
    
    // Authorization and success messages
    authSuccess: 'Authorization successful!',
    authProcessing: 'Completing authorization...',
    authProcessingDescription: 'Please wait, we are processing your Google authorization.',
    authErrorTitle: 'Authorization error',
    authRedirectMessage: 'You will be redirected to the home page...',
    returnToLogin: 'Return to login page',
    consultationStarted: 'Consultation started successfully',
    thanksForReview: 'Thank you for your feedback!',
    redirectingHome: 'Redirecting to home page...',
    emailVerified: 'Email verified successfully!',
    emailAlreadyVerified: 'Email was already successfully verified! Going to profile...',
    newVerificationSent: 'New verification link has been sent to the specified email',
    emailAlreadyConfirmed: 'already confirmed. Welcome!',
    emailSuccessfullyVerified: 'Email successfully verified. Welcome!',
    profileCreatedFromRegistration: 'Profile successfully created with registration data!',
    consultationRequestSent: 'Consultation request sent successfully!',
    pushNotificationsEnabled: 'Push notifications enabled!',
    passwordChanged: 'Password changed successfully',
    profilePhotoUpdated: 'Profile photo updated successfully',
    notificationSettingsSaved: 'Notification settings saved',
    accountDeleted: 'Account deleted successfully',
    reviewAlreadySent: 'Review has already been sent',
    reviewSent: 'Review sent successfully',
    avatarUpdated: 'Avatar updated successfully',
    consultationCompleted: 'Consultation completed successfully',
    consultationAutoCompleted: 'Consultation automatically completed due to message limit reached',
    
    // Additional translations for Google authorization
    attention: 'Attention',
    extensionWarning: 'Browser extensions detected that may interfere with the authorization process. If problems occur, try temporarily disabling extensions or using incognito mode.',
    authErrorCodeExpired: 'Authorization code has expired or is invalid. Please try logging in again.',
    authErrorCodeUsed: 'This authorization code has already been used. Please log in again.',
    authErrorGeneric: 'An error occurred while processing Google authorization. Please try again.',
    
    // Additional system messages
    connectionLost: 'Connection to server lost. Please try again later.',
    messageSendFailed: 'Failed to send message. Please try again.',
    connectionError: 'Failed to establish connection to server.',
    chatLoadError: 'Error loading chat. Please refresh the page.',
    serverConnectionFailed: 'Failed to connect to server',
    connectingToServer: 'Connecting to server...',
    finalizingConsultation: 'Finalizing consultation...',
    consultationCompletedSuccess: 'Consultation completed successfully',
    completionFailed: 'Failed to complete consultation. Please refresh the page and try again.',
    autoCompletionFailed: 'Failed to automatically complete consultation. Please contact the doctor.',
    messageLimitReached: 'Message limit reached. Consultation will be completed.',
    messageLimitAutoComplete: 'Consultation automatically completed due to message limit reached',
    connectionTimeout: 'Connection attempts exceeded. Please refresh the page.',
    unknownError: 'An unknown error occurred',
    statusActive: 'Active',
    statusCompleted: 'Completed',
    statusWaiting: 'Waiting',
    startChatMessage: 'Start the conversation by sending the first message',
    waitForStart: 'Wait for consultation to start',
    reviewFormError: 'Failed to open review form',
    messagePlaceholder: 'Enter message...',
    sendingDisabled: 'Message sending unavailable',
    messageLimitReachedStatus: 'Message limit reached',
    refreshChat: 'Refresh chat',
    loadingMessages: 'Loading messages...',
    finishConsultation: 'Finish consultation',
    noMessages: 'No messages',
    startConversation: 'Start the conversation by sending the first message',
    waitForConsultation: 'Wait for consultation to start',
    messagingDisabled: 'Message sending unavailable',
    enterMessage: 'Enter message...',
    messageLimitExceeded: 'You have reached the message limit for this consultation',
    completeConsultation: 'Complete consultation',
    confirmCompleteConsultation: 'Are you sure you want to complete the consultation? After completion, message sending will be unavailable.',
    patientCanLeaveReview: 'The patient will be able to leave a review about the consultation.',
    
    // Переводы для ReviewForm
    leaveReview: 'Leave Review',
    consultationWith: 'Consultation with',
    reviewHelpMessage: 'Your review will help other patients choose the right doctor. Thank you for your feedback!',
    rateConsultation: 'How do you rate the consultation?',
    ratingVeryBad: 'Very bad',
    ratingBad: 'Bad',
    ratingNormal: 'Normal',
    ratingGood: 'Good',
    ratingExcellent: 'Excellent',
    yourComment: 'Your comment',
    reviewCommentPlaceholder: 'Tell us about your consultation experience...',
    commentHelpText: 'Your comment will help the doctor improve the quality of consultations',
    submitReview: 'Submit Review',
    reviewSubmitError: 'Failed to submit review. Please try again later.',
    
    // Переводы для DoctorProfilePage
    bookConsultation: 'Book Consultation',
    doctorInfo: 'Doctor Information',
    practiceLocation: 'Practice Location',
    specializations: 'Specializations',
    consultationLanguages: 'Consultation Languages',
    doctorReviews: 'Doctor Reviews',
    reviewWithoutComment: 'Review without comment',
    doctorPracticeRegion: 'Doctor practice region',
    noDoctorReviews: 'This doctor has no reviews yet',
    beFirstToReview: 'Be the first to leave a review after consultation',
    
    // Переводы для SearchDoctorsPage
    findSpecialistDescription: 'Find the right specialist for consultation',
    searchInRegion: 'Search in region',
    autoFilterByRegion: 'Doctors are automatically filtered by your region. Can be changed in profile settings.',
    doctorsFound: 'Doctors found',
    searchResults: 'Search results',
    page: 'Page',
    of: 'of',
    noDoctorsFound: 'No doctors matching your search criteria',
    tryChangeSearchParams: 'Try changing search parameters or choosing a different specialization',
    
    // Переводы для HomePage
    findDoctorDescription: 'Search for doctors by specialization and book consultations',
    historyDescription: 'View your consultation history and payments',
    profileSettingsDescription: 'Update personal information and account settings',
    myConsultations: 'My Consultations',
    myConsultationsDescription: 'Manage current and upcoming consultations',
    doctorProfileDescription: 'Update professional information and schedule',
    analytics: 'Analytics',
    analyticsDescription: 'Consultation statistics and patient reviews',
    doctorWelcomeMessage: 'Here you can manage consultations and configure your profile.',
    patientWelcomeMessage: 'Here you can search for doctors, manage consultations and view history.',
    emailVerificationRequired: 'Email Verification Required',
    emailVerificationMessage: 'You cannot use the full functionality of the platform until you verify your Email. Please check your email and click the link in the message.',
    havingProblems: 'Having problems?',
    goTo: 'Go to',
    goToAdminPanel: 'Go to Admin Panel',
    contactSupport: 'Contact Support',
    systemManagement: 'System and user management',
    adminPanelDescription: 'Manage users and doctor applications',
    systemAnalytics: 'System Analytics',
    platformUsageStats: 'Platform usage statistics',
    featureInDevelopment: 'Feature in development',
        inDevelopment: 'In Development',
    
    // Переводы для AdminPage
    adminPanelTitle: 'Administrator Panel',
    systemUserManagement: 'System and user management',
    administrativePanel: 'Administrative Panel',
    account: 'Account',
    role: 'Role',
    administrator: 'Administrator',
    doctorApplications: 'Doctor Applications',
    doctorRoleApplications: 'Applications for doctor role',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    all: 'All',
    users: 'Users',
    userManagement: 'User Management',
    refreshList: 'Refresh List',
    noUsersInSystem: 'No users in the system',
    notifications: 'Notifications',
    notificationManagement: 'Notification Management',
    browserPushStatus: 'Browser push notifications status',
    browserSupport: 'Browser support',
    supported: 'Supported',
    notSupported: 'Not supported',
    permission: 'Permission',
    allowed: 'Allowed',
    blocked: 'Blocked',
    notDetermined: 'Not determined',
    requestPermission: 'Request permission',
    testBrowserNotifications: 'Test browser notifications',
    notificationTitle: 'Notification title',
    notificationText: 'Notification text',
    notificationType: 'Notification type',
    system: 'System',
    consultation: 'Consultation',
    appointment: 'Appointment',
    message: 'Message',
    update: 'Update',
    recipientParams: 'Recipient parameters',
    sendToAll: 'To all users',
    sendByRole: 'By user role',
    sendToSpecific: 'To specific user',
    selectRole: 'Select role',
    userIdForNotification: 'User ID for notification',
    sendNotification: 'Send notification',
    sendWebSocketNotifications: 'Send WebSocket notifications',
    personalData: 'Personal data',
    fullName: 'Full name',
    phoneNumber: 'Phone number',
    role: 'Role',
    registrationDate: 'Registration date',
    specialization: 'Specialization',
    changeRole: 'Change role',
    newRole: 'New role',
    
    // Статусы консультаций
    completed: 'Completed',
    active: 'Active',
    pending: 'Pending',
    cancelled: 'Cancelled',
    unknown: 'Unknown',
    
    // Дополнительные переводы для HistoryPage
    doctor: 'Doctor',
    patient: 'Patient',
    status: 'Status',
    creationDate: 'Creation date',
    startTime: 'Start time',
    noConsultationsHistory: 'You have no consultation history yet',
    loadingHistory: 'Loading history...',
    failedToLoadHistory: 'Failed to load consultation history. Please try again later.',
    failedToLoadUnreadMessages: 'Failed to load unread messages, using cached data',
    
    // Переводы для PatientProfileForm
    consultationHistoryWillBeUnavailable: 'Consultation history will be unavailable',
    editProfile: 'Edit profile',
    saveProfile: 'Save profile',
    cancelEditing: 'Cancel editing',
    changePassword: 'Change password',
    notificationSettings: 'Notification settings',
    privacySettings: 'Privacy settings',
    deleteAccount: 'Delete account',
    currentPassword: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm password',
    emailNotifications: 'Email notifications',
    pushNotifications: 'Push notifications',
    appointmentReminders: 'Appointment reminders',
    medicalInfo: 'Medical information',
    medicalInfoPlaceholder: 'Chronic diseases, allergies, medications taken...',
    profileImageUpload: 'Profile image upload',
    selectPhoto: 'Select photo',
    changePhoto: 'Change photo',
    profileSaved: 'Profile saved',
    profileSaveError: 'Error saving profile',
    passwordChanged: 'Password changed',
    passwordChangeError: 'Error changing password',
    notificationSettingsUpdated: 'Notification settings updated',
    deleteAccountConfirmation: 'Are you sure you want to delete your account?',
    thisActionCannotBeUndone: 'This action cannot be undone',
    selectRegion: 'Select region',
    selectDistrict: 'Select district',
    
    // Переводы для RequestConsultationModal
    youAlreadyHaveConsultation: 'You already have a consultation',
    consultationApplication: 'Consultation application',
    consultationRequestSent: 'Consultation request sent',
    consultationRequestError: 'Error sending consultation request',
    consultationAlreadyActive: 'You already have an active consultation with this doctor',
    goToConsultations: 'Go to consultations',
    close: 'Close',
    existingConsultationMessage: 'You already have an active consultation with the doctor',
    goToHistoryToContact: 'You can go to consultation history to continue communication in the existing consultation.',
    format: 'Format',
    chatConsultation: 'Chat consultation',
    messageLimit: 'Message limit',
    messageCountInfo: '30 messages (with extension option)',
    noteToDoctor: 'Note for doctor (optional)',
    notePlaceholder: 'Describe your symptoms or questions you would like to discuss with the doctor...',
    send: 'Send'
    }
  };

// Контекст для языка
export const LanguageContext = React.createContext({
  currentLanguage: 'ru',
  setLanguage: () => {},
  t: (key) => key,
  languages: AVAILABLE_LANGUAGES
});

// Хук для использования переводов
export const useTranslation = () => {
  const context = React.useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};

// Провайдер языка
export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('ru');
  
  // Загружаем сохраненный язык при инициализации
  useEffect(() => {
    const savedLanguage = localStorage.getItem('preferred_language');
    if (savedLanguage && AVAILABLE_LANGUAGES.find(lang => lang.code === savedLanguage)) {
      setCurrentLanguage(savedLanguage);
    }
  }, []);
  
  // Функция для смены языка
  const setLanguage = (languageCode) => {
    setCurrentLanguage(languageCode);
    localStorage.setItem('preferred_language', languageCode);
  };
  
  // Функция перевода
  const t = (key) => {
    return translations[currentLanguage]?.[key] || translations.ru[key] || key;
  };
  
  const value = {
    currentLanguage,
    setLanguage,
    t,
    languages: AVAILABLE_LANGUAGES
  };
  
  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

// Компонент селектора языка
const LanguageSelector = ({ variant = 'dropdown', className = '' }) => {
  const { currentLanguage, setLanguage, languages } = useTranslation();
  const [isOpen, setIsOpen] = useState(false);
  
  const currentLang = languages.find(lang => lang.code === currentLanguage) || languages[0];
  
  if (variant === 'button') {
    return (
      <div className={`relative ${className}`}>
        <Button
          variant="light"
          size="sm"
          startContent={<FiGlobe size={16} />}
          onPress={() => setIsOpen(!isOpen)}
          className="text-sm"
          style={{ color: brandColors.primary[600] }}
        >
          {currentLang.nativeName}
        </Button>
        
        {isOpen && (
          <div 
            className="absolute top-full right-0 mt-2 bg-white rounded-lg shadow-lg border z-50 min-w-[150px]"
            style={{ borderColor: brandColors.neutral[200] }}
          >
            {languages.map((lang) => (
              <button
                key={lang.code}
                onClick={() => {
                  setLanguage(lang.code);
                  setIsOpen(false);
                }}
                className={`w-full text-left px-3 py-2 text-sm hover:bg-gray-50 first:rounded-t-lg last:rounded-b-lg transition-colors ${
                  lang.code === currentLanguage ? 'font-medium' : ''
                }`}
                style={{ 
                  color: lang.code === currentLanguage ? brandColors.primary[600] : brandColors.neutral[700],
                  backgroundColor: lang.code === currentLanguage ? brandColors.primary[50] : 'transparent'
                }}
              >
                <div className="flex items-center justify-between">
                  <span>{lang.nativeName}</span>
                  {lang.code === currentLanguage && (
                    <span style={{ color: brandColors.primary[500] }}>✓</span>
                  )}
                </div>
              </button>
            ))}
          </div>
        )}
        
        {/* Backdrop для закрытия dropdown */}
        {isOpen && (
          <div 
            className="fixed inset-0 z-40" 
            onClick={() => setIsOpen(false)}
          />
        )}
      </div>
    );
  }
  
  return (
    <Select
      size="sm"
      selectedKeys={[currentLanguage]}
      onSelectionChange={(keys) => {
        const selected = Array.from(keys)[0];
        if (selected) {
          setLanguage(selected);
        }
      }}
      startContent={<FiGlobe size={16} />}
      className={className}
      classNames={{
        trigger: "h-10",
        value: "text-sm"
      }}
      placeholder="Select language"
    >
      {languages.map((lang) => (
        <SelectItem key={lang.code} value={lang.code}>
          {lang.nativeName}
        </SelectItem>
      ))}
    </Select>
  );
};

export default LanguageSelector;
export { LanguageSelector }; 